# Generated by Django 4.2.5 on 2023-10-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono_movil', models.CharField(max_length=15)),
                ('tipo_usuario', models.CharField(choices=[('administrador', 'Administrador'), ('soporte_tecnico', 'Soporte Técnico')], max_length=20)),
            ],
        ),
    ]
