# Generated by Django 4.2.5 on 2023-10-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosInternet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_plan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inpuesto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('no_crear_reglas', models.BooleanField(default=False)),
                ('descarga_kbps', models.IntegerField()),
                ('subida_kbps', models.IntegerField()),
                ('limit_AT', models.IntegerField()),
                ('burst_limit', models.IntegerField()),
                ('burst_threshold', models.IntegerField()),
                ('burst_time', models.IntegerField()),
                ('prioridad', models.PositiveIntegerField()),
                ('addresslist', models.CharField(max_length=100)),
                ('parent', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosPersonalizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inpuestos', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Clave', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioTelefonico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minutos', models.IntegerField()),
                ('costo_tel_fijo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('costo_tel_movil', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.TextField()),
                ('notas', models.TextField(blank=True)),
            ],
        ),
    ]
