# Generated by Django 4.2.5 on 2023-11-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_remove_serviciosinternet_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciosinternet',
            name='prifile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
