# Generated by Django 4.2.5 on 2023-10-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedesIpv4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('redip', models.CharField(max_length=100)),
                ('uso_ipc', models.CharField(max_length=100)),
                ('cibr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_router', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('usuario_api', models.CharField(blank=True, max_length=100, null=True)),
                ('contrasenia_api', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_router', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('seguridad', models.CharField(blank=True, max_length=100, null=True)),
                ('seguridad_alternativa', models.CharField(blank=True, max_length=100, null=True)),
                ('configuracion_radius', models.CharField(blank=True, max_length=100, null=True)),
                ('radius_nas_ip', models.CharField(blank=True, max_length=80, null=True)),
                ('registro_trafico', models.CharField(blank=True, max_length=100, null=True)),
                ('control_velocidad', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
