# Generated by Django 4.2.5 on 2023-10-31 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_red', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redesipv4',
            name='router',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redes_ipv4', to='gestion_red.router'),
        ),
    ]
