# Generated by Django 4.2.5 on 2023-10-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_red', '0004_alter_monitoreo_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
