# Generated by Django 4.2.5 on 2023-10-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_red', '0005_alter_monitoreo_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='napcaja',
            name='proveedor_internet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
