# Generated by Django 4.2.5 on 2023-11-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_red', '0006_alter_napcaja_proveedor_internet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='napcaja',
            name='en_operacion',
        ),
        migrations.RemoveField(
            model_name='napcaja',
            name='proveedor_internet',
        ),
        migrations.AddField(
            model_name='napcaja',
            name='coordenadas',
            field=models.CharField(default=':', max_length=200),
        ),
    ]
