# Generated by Django 4.2.5 on 2023-11-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_red', '0007_remove_napcaja_en_operacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OltDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('olt_hardware_version', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('telnet_port', models.IntegerField()),
                ('snmp_port', models.IntegerField()),
            ],
        ),
    ]
