# Generated by Django 4.2.5 on 2023-11-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_red', '0008_oltdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oltdevice',
            name='ip',
            field=models.CharField(max_length=100),
        ),
    ]
