# Generated by Django 4.2.5 on 2023-11-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_red', '0010_alter_oltdevice_snmp_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='napcaja',
            name='fecha_instalacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
