# Generated by Django 5.0.3 on 2024-05-09 21:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=250)),
                ('stock_actual', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContratosFucionador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('productos', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(max_length=250)),
                ('nombre_usuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(blank=True, max_length=250, null=True)),
                ('nombre_producto', models.CharField(blank=True, max_length=250, null=True)),
                ('historial', models.JSONField(blank=True, null=True)),
                ('nombre_solicitante', models.CharField(blank=True, max_length=250, null=True)),
                ('uso', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_instalacion', models.DateField(auto_now_add=True)),
                ('telefono_cliente', models.CharField(max_length=13)),
                ('nombre_cliente', models.CharField(max_length=250)),
                ('tipo_servicio', models.CharField(max_length=250)),
                ('nombre_instalador', models.CharField(blank=True, max_length=250, null=True)),
                ('direccion_cliente', models.CharField(blank=True, max_length=250)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('prefirma_trabajador', models.JSONField(null=True)),
                ('prefirma_cliente', models.JSONField(null=True)),
                ('informacionFibra', models.JSONField(null=True)),
                ('informacionAntena', models.JSONField(null=True)),
                ('archivoTerminal', models.FileField(blank=True, null=True, upload_to='evidencias/terminal/')),
                ('archivoRouter', models.FileField(blank=True, null=True, upload_to='evidencias/router/')),
                ('archivoPTerminal', models.FileField(blank=True, null=True, upload_to='evidencias/pterminal/')),
                ('archivoPosicionAntena', models.FileField(blank=True, null=True, upload_to='evidencias/posicionAntena/')),
                ('archivoInformacionAntena', models.FileField(blank=True, null=True, upload_to='evidencias/informacionAntena/')),
                ('archivoNavegacion', models.FileField(blank=True, null=True, upload_to='evidencias/navegacion/')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('cantidad', models.IntegerField()),
                ('modelo', models.CharField(max_length=250, null=True)),
                ('unidad', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermisosProductosFucionador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PermisosProductosTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, max_length=250, null=True)),
                ('codigoInterno', models.CharField(max_length=10, null=True)),
                ('marca', models.CharField(blank=True, max_length=250, null=True)),
                ('modelo', models.CharField(blank=True, max_length=250, null=True)),
                ('stock', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=250, null=True)),
                ('empresa', models.CharField(blank=True, max_length=250, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=250, null=True)),
                ('zona', models.CharField(blank=True, max_length=250, null=True)),
                ('stock_minimo', models.IntegerField(null=True)),
                ('imgProducto', models.FileField(blank=True, null=True, upload_to='imgProducto/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('categoria', models.CharField(max_length=250, null=True)),
                ('fecha_actualizacion', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre_completo', models.CharField(max_length=250)),
                ('correo_electronico', models.CharField(max_length=250)),
                ('numero_celular', models.CharField(max_length=15)),
                ('equipo_trabajo', models.TextField()),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_nacimiento', models.DateField()),
                ('fotoPerfil', models.FileField(blank=True, null=True, upload_to='fotosPerfiles/')),
                ('ubicacion', models.CharField(max_length=250)),
                ('tipo_rol', models.CharField(max_length=250)),
                ('password', models.CharField(default='NA', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZonaUsoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(blank=True, max_length=250, null=True)),
                ('fraccionamiento', models.CharField(blank=True, max_length=250, null=True)),
                ('colona', models.CharField(blank=True, max_length=250, null=True)),
                ('juntaAuxiliar', models.CharField(blank=True, max_length=250, null=True)),
                ('productos', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosIndividuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto_individual', models.CharField(max_length=250)),
                ('status', models.BooleanField()),
                ('codigo_barras', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.CharField(max_length=200, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaSolit.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falla_descripcion', models.TextField()),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
                ('status', models.SmallIntegerField()),
                ('id_producto_individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaSolit.productosindividuales')),
            ],
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('nombre_administrador', models.CharField(blank=True, max_length=250, null=True)),
                ('producto_cantidad', models.JSONField(null=True)),
                ('nombre_solicitante', models.CharField(max_length=250, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaSolit.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Carretes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metraje_inicial', models.IntegerField()),
                ('metraje_usado', models.IntegerField(blank=True, null=True)),
                ('luegarDeUso', models.CharField(blank=True, max_length=250, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('id_producto_individual', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaSolit.productosindividuales')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaSolit.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AlmacenSolit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_entrada', models.DateTimeField()),
                ('cantidad_entrada', models.IntegerField()),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
                ('cantidad_salida', models.IntegerField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaSolit.productos')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaSolit.usuario')),
            ],
        ),
    ]
