# Generated by Django 5.0.3 on 2024-05-11 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carretes',
            name='id_producto_individual',
        ),
        migrations.AddField(
            model_name='carretes',
            name='id_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaSolit.productos'),
        ),
    ]
