# Generated by Django 5.0.3 on 2024-05-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0002_remove_carretes_id_producto_individual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='equipo_trabajo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
