# Generated by Django 5.0.3 on 2024-05-16 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0003_alter_usuario_equipo_trabajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonausomaterial',
            name='productos',
        ),
        migrations.AddField(
            model_name='reparto',
            name='id_zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaSolit.zonausomaterial'),
        ),
    ]
