# Generated by Django 5.0.3 on 2024-05-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0004_remove_zonausomaterial_productos_reparto_id_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonausomaterial',
            name='productos',
            field=models.JSONField(null=True),
        ),
    ]
