# Generated by Django 5.0.3 on 2024-05-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0007_pedido_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='automatico_insert',
            field=models.BooleanField(default=False),
        ),
    ]
