# Generated by Django 5.0.3 on 2024-05-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0010_auditlog_delete_logentry_calendario_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
