# Generated by Django 5.0.3 on 2024-05-31 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0012_alter_usuario_correo_electronico'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombrePdfsSubidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePdf', models.CharField(max_length=255)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
