# Generated by Django 5.0.3 on 2024-05-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0013_nombrepdfssubidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='nombrepdfssubidos',
            name='nameUser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
