# Generated by Django 5.0.3 on 2024-06-03 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0014_nombrepdfssubidos_nameuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pdf_subido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='sistemaSolit.nombrepdfssubidos'),
        ),
    ]
