# Generated by Django 5.0.3 on 2024-06-04 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0015_pedido_pdf_subido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonasAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreZona', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='ZonaAlmacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemaSolit.zonasalmacen'),
        ),
    ]
