# Generated by Django 5.0.3 on 2024-06-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0018_reparto_nombrecliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparto',
            name='idSolicitante',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
