# Generated by Django 5.0.3 on 2024-06-07 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0019_reparto_idsolicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='productoParaPrestar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductosPrestados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(blank=True, max_length=250, null=True)),
                ('nombre_producto', models.CharField(blank=True, max_length=250, null=True)),
                ('codigoInterno', models.CharField(max_length=10, null=True)),
                ('marca', models.CharField(blank=True, max_length=250, null=True)),
                ('modelo', models.CharField(blank=True, max_length=250, null=True)),
                ('stock', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=250, null=True)),
                ('empresa', models.CharField(blank=True, max_length=250, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=250, null=True)),
                ('zona', models.CharField(blank=True, max_length=250, null=True)),
                ('stock_minimo', models.IntegerField(null=True)),
                ('categoria', models.CharField(max_length=250, null=True)),
                ('fecha_actualizacion', models.DateField(null=True)),
                ('automatico_insert', models.BooleanField(default=False)),
                ('ZonaAlmacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemaSolit.zonasalmacen')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
