# Generated by Django 5.0.3 on 2024-06-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0020_productos_productoparaprestar_productosprestados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosprestados',
            name='ZonaAlmacen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
