# Generated by Django 5.0.3 on 2024-06-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0021_alter_productosprestados_zonaalmacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='productoParaPrestar',
            field=models.BooleanField(default=False),
        ),
    ]
