# Generated by Django 5.0.3 on 2024-06-07 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0022_alter_productos_productoparaprestar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparto',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='reparto',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
