# Generated by Django 5.0.3 on 2024-06-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0023_remove_reparto_id_usuario_reparto_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparto',
            name='TipoUsio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
