# Generated by Django 5.0.3 on 2024-06-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0024_reparto_tipousio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='title',
            field=models.CharField(max_length=600),
        ),
    ]
