# Generated by Django 5.0.3 on 2024-06-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0025_alter_calendario_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSolicitante', models.CharField(max_length=200)),
                ('producto', models.JSONField(null=True)),
                ('fecha_uso', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
