# Generated by Django 5.0.3 on 2024-06-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSolit', '0026_devoluciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='productoParaPrestar',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
