# Generated by Django 4.2.5 on 2023-10-19 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('nombres_apellidos', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('telefono_casa', models.CharField(max_length=20)),
                ('telefono_movil', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_hora_instalacion', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('dia_pago', models.PositiveIntegerField()),
                ('crear_factura', models.CharField(max_length=50)),
                ('tipo_impuesto', models.CharField(max_length=50)),
                ('dias_gracia', models.CharField(max_length=50)),
                ('aplicar_corte', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mora', models.BooleanField(default=False)),
                ('reconexion', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviso_nueva_factura', models.BooleanField(default=False)),
                ('aviso_en_pantalla', models.BooleanField(default=False)),
                ('recordatorio_pago', models.BooleanField(default=False)),
                ('recordatorio1', models.BooleanField(default=False)),
                ('recordatorio2', models.BooleanField(default=False)),
                ('recordatorio3', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OtrosImpuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inpuesto1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('inpuesto2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('inpuesto3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('facturacion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.facturacion')),
            ],
        ),
    ]
