# Generated by Django 4.2.5 on 2023-10-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='fecha_hora_instalacion',
        ),
    ]
