# Generated by Django 4.2.5 on 2023-11-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_clientes_correo_alter_clientes_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
