# Generated by Django 5.0 on 2023-12-27 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0005_instalacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='valor_por_defecto', max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('ubicacion', models.CharField(blank=True, default='valor_por_defecto', max_length=300, null=True)),
                ('Nombre', models.CharField(blank=True, max_length=355, null=True)),
                ('descripcion', models.CharField(blank=True, default='valor_por_defecto', max_length=300, null=True)),
                ('marca', models.CharField(blank=True, default='valor_por_defecto', max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, default='valor_por_defecto', max_length=50, null=True)),
                ('Stock', models.IntegerField(blank=True, null=True)),
                ('Precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proveedor', models.CharField(max_length=100, null=True)),
                ('Telefono', models.CharField(max_length=50)),
                ('Gmail', models.CharField(max_length=50, null=True)),
                ('Direccion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, null=True)),
                ('Direccion', models.CharField(max_length=90, null=True)),
                ('nivel_Educativo', models.CharField(default='NA', max_length=100)),
                ('habilidates', models.CharField(default='NA', max_length=100)),
                ('evaluacion', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Insta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('instalacion', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.instalacion')),
                ('productos', models.ManyToManyField(related_name='Accesorios_del_tecnico', to='almacen.producto')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='almacen.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.PositiveBigIntegerField(default=0)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.insta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='Proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.proveedor'),
        ),
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, null=True)),
                ('Stock', models.IntegerField()),
                ('Precio', models.IntegerField()),
                ('ID_Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.proveedor')),
            ],
        ),
    ]
