# Generated by Django 5.0 on 2023-12-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_producto_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='Image Base64'),
        ),
    ]
